"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files":
  [
    {
      "source": "src/_locales/en/messages.json",
      "translation": "src/_locales/%two_letters_code%/messages.json",
      "languages_mapping":
        {
          "two_letters_code":
            { "zh-CN": "zh_CN", "nn-NO": "nn", "sv-SE": "sv" },
        },
    },
  ]
