name: Release extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Generate release tag
      id: tag
      run: |
          echo "::set-output name=release_tag::IDAC_$(date +"%Y.%m.%d_%H-%M")"

    - name: Move to manifest v3
      run: |
        cp src/manifest_v3.json src/manifest.json 

    - name: Archive Release
      run: |
        7z a 'IDCAC-chrome.zip' -r './src/*'

    - uses: actions/upload-artifact@v3
      with:
        name: IDCAC-chrome
        path: 'IDCAC-chrome.zip'

    - name: Move to manifest v2
      run: |
        rm src/manifest.json
        cp src/manifest_v2.json src/manifest.json 
        
    - name: "web-ext build"
      id: web-ext-build
      uses: kewisch/action-web-ext@v1
      with:
        cmd: build
        source: src
        filename: "IDCAC.xpi"

    - uses: actions/upload-artifact@v3
      with:
        name: IDCAC-firefox-unsigned
        path: ${{ steps.web-ext-build.outputs.target }}

    - name: "web-ext sign"
      id: web-ext-sign
      uses: kewisch/action-web-ext@v1
      with:
        cmd: sign
        source: ${{ steps.web-ext-build.outputs.target }}
        channel: unlisted
        apiKey: ${{ secrets.AMO_SIGN_KEY }}
        apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
        timeout: 900000
        
    - uses: actions/upload-artifact@v3
      with:
        name: IDCAC-firefox-signed
        path: ${{ steps.web-ext-sign.outputs.target }}

    - name: Rename xpi
      run: |
        mv ${{ steps.web-ext-sign.outputs.target }} IDCAC-firefox.xpi

    - name: "Create Release"
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          draft: true
          files: |
            IDCAC-chrome.zip
            IDCAC-firefox.xpi
            
            
        

          
